db.url=jdbc:postgresql://localhost:5432/payment_system
db.username=postgres
db.password=06051987

db.driverClassName=org.postgresql.Driver
db.pool.size=10
db.pool.idle.timeout=300000
db.pool.max.lifetime=1200000
db.pool.connection.timeout=20000
db.pool.leak.detection.threshold=30000