db.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=bank-schema
db.username=postgres
db.password=root
db.driver=org.postgresql.Driver

account.default-amount=0.0
account.transfer-commission=0.02

